language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "needles-and-cones-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
  #before_deploy: # omit node_modules, since we set skip_cleanup below
  #- rm -rf node_modules
  # deploy: # see README for details on these keys
  # prevents travis from deleting the build
  # skip_cleanup: true #: now deprecated - cleanup is now false by default
  # provider: heroku
  # app should be your heroku app name; see README
  # app: needles-and-cones
  # the secure key indicates an encrypted value; see README
  # api_key:
  #  secure:    DFL7UBv7ZalDF8zK62cZlQH5vc6G9IFW2qgo80HntRyUr820UUkWWkf39LFSrPHevsij9mvTfqdLv4yg+q8n8fLfY9aTIy3MzNzOxkhZ3g/sWknzymu8S4yB8BVIn5/9QpRyKjj4JLM8j26KZmc+TVzDFOrhG/+qMWEq275pTzMV4Utdx+eo33wA91/bwi0s3MClbUIQlNTmvJw4ek3+UlhfEYXJJppUMroVVcdCkGmsFkmjGWy1oPFpCp/zJWQ/lwGUmYmc9oE8EYBPEmDAS/Lb7CkdtN2UBo+a9iLJ4G/KH2FXWA3F/HB/Q2W4C7YSG4ng86iMXAEYonUNP9AkmD2NWcFenF6QngbnCwke4hBt3U7/Rm80lbHNroS/rnOaXd5DVCxDQAEYX1zD7hCnWQeYyoLrQUKO2EGqweyeUAVbhejCjbNzlnIFt+TDRYT5SdKXBJvGgjiij4Tu1u6yZwVioAIzHw4SqTE4kX+a4Yzlb+HN8NkQUa1M5G/qjK6GsRtdFjE0GP7xDfNtOJqUhK6CGJwgjvdyXHuJ6EVPygkwMf9cC142Le2lAiwLHQy65t/Gb0VxVvmJzx83g/NkCe3zb1gv52cB8vvK1NVbwo562+VULc/cuUS/eOrwx2kuQO7WBYMbUrfIVxowiIbF6LvMCsWHHEcV7MbUragl7Z4=
  #on:
  #branch: main
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  provider: heroku
  # app should be your heroku app name; see README
  app: needles-and-cones
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: XWj4LQsuObIhh/DyU6YhQKZ5Aa4sbehIZ9qs94PS+xenQpbVrUvOxXll2evu/BgZnCbeAgcD6rCRjkPcWybBqZ7MSSur0ONRgkKlHW8Mc+zwb2rjXFZjn8vcZKvHeDajnHJX8HhXr1iNOaQHtwUfebEowJnhiIPhZsEkXUgldanIq/1H7vOEk5KFxHMtmPK2/CNoy+SSZPDVAdr69yashdXNK0LIbifFJM5n/L+mX2JUq0w9wFxXWXSVYFxeo2dyFjKY/AOuum7H5zMXpxXjfUuHoAmWM6DZ2jeudgyor+RnnN/lC6l2704kJ1LowOncYw7V6XeifeMRw7Zf85imKPFhiy5mVndzWOeu/jBfrY3r46C8EHxkc43tJCacbiSRn2ZOf5y2V6w4x9zMaeSt8tqkUO0s74tFPi57UDJ+InKF3RxNWfpoPoe7LA3befB8bpAmPYJ1EEXBMMigHUGXVIMsf4mgqQQnYXuxmXRarrQWrcd/FkLP9xGkoNLrz3KSTGQYPV7Yfg17HvLniay3zz9hM1Xk1sf4/r/nckPYhXwwMIUJmyh0cmZeKacfNv8D0qs5fKMKujxLTkWRW6/Qb//0W0mY6UbO1HWBQ2fYs/yk1M6qzVZOBxCwFX5wCnytio9rzSHXAPlpd0LaZ9hk9Qtr5JpWh6mlnEJHFQn5Kps=
  strategy: git
  on:
    branch: main
